### PR TITLE
WIP: Feature/transformer update

### PR DESCRIPTION
**Pull request by chrisdrackett**
starting to think about how transformers work. The idea behind this (admittedly ambitious) PR is the following:

1. `unicon` itself gets svgs from various sources and cleans them up and provides them as a list of svg objects.
2. transformers then take that object and output it. the `unicon-transformer-js` will output things like the old `unicon-transformer-json` transformer
3. added a new `unicon-transformer-json` that outputs a valid `.json` file with the svgs.
4. moving file output from `unicon-cli` to be something transformers handle. This might need a bit of work still.

### CODE REVIEW

**Comment by chrisdrackett** [comment]
@souporserious curious your thoughts on this! I have the following working:

By default `unicon folder input --output output` will take all the svgs from `input` and optimize them and dump them in `output`. Not sure exciting for a folder, but exciting for figma and/or sketch.

If you add `--transformer json` you'll get a `svgs.json` file within the output directory that can then be used in JS however you want.

Lastly if you add `--transformer js` you'll get the same output the old `json` transformer output.

**Comment by souporserious** [comment]
Thanks for adding all of this Chris! 🙏 I have a busy week ahead of me, but I'll take a look and comment as soon as I get a chance.

**Comment by chrisdrackett** [comment]
I’m going to be integrating this in our app next week so might be making adjustments. If you think it looks good I’ll also look into updating docs and other things as well :)

**Comment by souporserious** [comment]
Finally got a chance to review this 😁. Everything is looking great! My only concern is moving the SVGO optimization to the `unicon` package. My original thinking behind not having it there was it could just source the raw data for you without any transformation. I didn't want to pigeonhole people into having to use SVGO, although guessing they probably would 🤷‍♂️ . Also inspired by what [`svgson`](https://www.npmjs.com/package/svgson) did with their [next version](https://github.com/elrumordelaluz/svgson-next).

Maybe we could allow stacking transforms similar to Babel/Webpack? Then you could have an optimization transform (SVGO), then use another transform to output JSON, JS or whatever. Actually, I'm wondering if _writing_ a file is different than _transforming_ it, maybe that should be rearchitected somehow 🤔. Any thoughts there?

**Comment by chrisdrackett** [comment]
I actually did some thinking about that, but personally could not think of a use case where I would not want to optimize an SVG or a use case where I would want to transform the base SVG in any way. I can think of lots of use cases for outputting the optimized SVG in a lot of different ways so the current transformer piece makes a lot of sense to me.

One thought is to have optimization be controllable with a boolean and/or set of options?

Another, like you mentioned is adding a new option around `processor` or similar (or you rename `transform`).

If this were my library I would probably start simple with just transformers (I'm biased as thats all I need) and expand the idea of processors if and when there is a need.

**Comment by chrisdrackett** [comment]
@souporserious I've (finally) found some time to work on this some more. As it's been a good amount of time (and I see you are working on an icon, yay!) I wanted to check in to see if its still valuable for me to explore the ideas proposed by this PR. Have you done any work on this package behind the scenes recently?

**Comment by souporserious** [comment]
@chrisdrackett excited to hear you're still interested! I've done some experimenting behind the scenes. I was going to post a PR to discuss some ideas I had. I was thinking of reworking `transformers` to work like plugins which could either be used to transform sourced data or create files. This would be really similar to [Gatsby plugins](https://www.gatsbyjs.org/docs/plugin-authoring/#plugin-naming-conventions).

That way you could have something like this:

```js
module.exports = {
  plugins: [
    "unicon-transformer-svgo",
    "unicon-transformer-json",
    "unicon-file-json"
  ],
}
```

I'm still conflicted though 😅. I'm wondering where the file creation process should take place. Similar to what you said before, maybe it's premature to split things out this much and one plugin or transformer could take care of manipulating the SVG data as well as creating the file. Would love to hear any new thoughts you have on this 😁.

**Comment by chrisdrackett** [comment]
Here is my current thinking about this group of packages:

```
Importer (figma, file, sketch, etc?) -> Internal Optimize/Process (Optimize Optional?) -> Transformer (js, json, template, etc)
```

I could see updating the importer piece to be pluggable so if someone wanted to add an illustrator importer or similar it would be possible.

I could also see adding a switch for the optimize step if there is a good use case (I don't currently know of a use-case, but maybe some svgs can get mangled?)

As for the transformer piece, at least in my use so far I don't see a need for more than one. I could see how the svgo piece could be seen as a transform, but other than running that I'm not sure of anything else you would want to do to the SVG in addition to getting it in the output format you want that wouldn't be easer in the design tool or in code after the SVG is transformed.

so I guess my two cents are to keep the optimize piece internal as I guess that for most (if not all?) use-cases doing that is a good idea. If there are usecases where that might mangle an SVG maybe it makes sense to add a way to turn it off?

I'm currently using the json transformer I wrote with something similar to your unicon-react and I find it very flexible. I currently run unicon twice, once for my icons and once for a set of illustrations. I then just have 2 different react components that consume each of the respective `.json` files.

**Comment by souporserious** [comment]
Thanks for the input Chris! This is all great feedback. I've been thinking through this all week and trying out different examples and I'm coming to the conclusion maybe a cli tool doesn't make sense for Unicon.

In a simple use case, a custom build setup is somewhat small:

```js
const fs = require('fs')
const path = require('path')
const pascalcase = require('pascalcase')
const svgo = require('svgo')
const svgson = require('svgson')
const { getSvgsFromFigma, setFigmaToken } = require('unicon')
const util = require('util')

function optimizeSvg(svg) {
  return new svgo({
    multipass: true,
  })
    .optimize(svg)
    .then(({ data }) => data)
}

function svgToJSON(svg) {
  return svgson(svg, {
    camelcase: true,
  })
}

setFigmaToken('some-token-here')

getSvgsFromFigma('ZnDGRhPTtScYMW2hYXyodJub', {
  transformSvg: [optimizeSvg, svgToJSON],
}).then(svgs => {
  fs.writeFileSync(
    path.resolve('./src/icons.js'),
    Object.keys(svgs)
      .map(
        key =>
          `export const ${pascalcase(key)} = ${util.inspect(svgs[key], {
            breakLength: Infinity,
            depth: null,
          })}`
      )
      .join('\n')
  )
})
```

This gives the end user pretty much full control of how the SVGs are output and keeps the focus of Unicon on just getting the SVG data. Thinking there could be official examples with other libraries like [`svgson`](https://github.com/elrumordelaluz/svgson#readme) or [`svgr`](https://github.com/smooth-code/svgr) as well as some small utilities to help with the above if it makes sense.

Tying into NPM scripts would be pretty easy through Node since it could be something as simple as this:

```json
{
  "scripts": {
    "icons": "node ./unicon.config.js"
  }
}
```

Thoughts on that? In some ways, this isn't as simple as the cli, but I like that it forces you into a Node environment which gives you full flexibility and doesn't require Unicon to support a ton of options or really make any opinions.

**Comment by chrisdrackett** [comment]
yeah, at least in my use-cases I wouldn't have to change much to support this. The CLI might offer some niceties like logging, etc. that with this approach you would need to do yourself.

That being said, I wonder if there are people who just want to get the svg files and don't want to write a script. Even if you provide good script examples there is something to be said to the simplicity or just downloading `unicon-cli` and adding a single line to your package.json to get up and running. Food for thought!

**Comment by chrisdrackett** [comment]
My personal vote would probably be to go this no-cli way to start as it is much simpler, fyi, just wanted to play a little devils advocate :)

**Pull request closed without merging**
